/*
====================================================================================================================
Magnitude Analysis
====================================================================================================================
Purpose:
    - Analyze the distribution and magnitude of key business metrics across different dimensions.
    - Understand customer distribution by country and gender.
    - Analyze product distribution and costs by category.
    - Identify revenue and quantity contribution across categories, customers, and countries.

SQL Functions Used:
    - COUNT()
    - AVG()
    - SUM()
====================================================================================================================
*/


/* -----------------------------------------------------------------------------------------------------------------
1) Analyze Customer Distribution by Country
   - Identify the number of customers in each country.
-------------------------------------------------------------------------------------------------------------------*/

Select 
	Country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

/* -----------------------------------------------------------------------------------------------------------------
2) Analyze Customer Distribution by Gender
   - Identify the number of customers in each gender category.
-------------------------------------------------------------------------------------------------------------------*/

Select 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

/* -----------------------------------------------------------------------------------------------------------------
3) Analyze Product Distribution by Category
   - Identify the number of products available in each category.
-------------------------------------------------------------------------------------------------------------------*/

Select 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_product
GROUP BY category
ORDER BY total_products DESC;

/* -----------------------------------------------------------------------------------------------------------------
4) Analyze Average Product Cost by Category
   - Calculate the average product cost within each category.
-------------------------------------------------------------------------------------------------------------------*/

Select 
	category,
	AVG(cost) AS average_cost
FROM gold.dim_product
GROUP BY category
ORDER BY average_cost DESC;

/* -----------------------------------------------------------------------------------------------------------------
5) Analyze Revenue by Product Category
   - Identify the total revenue generated by each product category.
-------------------------------------------------------------------------------------------------------------------*/

Select 
	GP.category,
	SUM(GS.sales_amount) AS total_revenue
FROM gold.fact_sales AS GS
LEFT JOIN gold.dim_product AS GP
	ON GS.product_key = GP.product_key
GROUP BY GP.category
ORDER BY total_revenue DESC;

/* -----------------------------------------------------------------------------------------------------------------
6) Analyze Revenue by Customer
   - Identify the total revenue generated by each customer.
-------------------------------------------------------------------------------------------------------------------*/

Select 
	GC.customer_id,
	GC.first_name,
	GC.last_name,
	SUM(GS.sales_amount) AS total_revenue
FROM gold.fact_sales AS GS
LEFT JOIN gold.dim_customers AS GC
	ON GS.customer_key = GC.customer_key
GROUP BY GC.customer_id,
	GC.first_name,
	GC.last_name
ORDER BY total_revenue DESC;


/* -----------------------------------------------------------------------------------------------------------------
7) Analyze Quantity Sold by Country
   - Identify the total quantity of products sold in each customer country.
-------------------------------------------------------------------------------------------------------------------*/

Select 
	GC.country,
	SUM(GS.quantity) AS total_sold_items
FROM gold.fact_sales AS GS
LEFT JOIN gold.dim_customers AS GC
	ON GS.customer_key = GC.customer_key
GROUP BY GC.country
ORDER BY total_sold_items DESC;
